version: '3.8'
name: grafana
services:
  mimir:
    image: grafana/mimir:2.11.0
    container_name: mimir
    command: ["--config.file=/etc/grafana/config.yaml"]
    environment:
    - "JAEGER_AGENT_HOST=agent"
    - "JAEGER_AGENT_PORT=6831"
    - "JAEGER_SAMPLER_TYPE=const"
    - "JAEGAR_SAMPLER_PARAM=1"
    ports:
    - "8080:8080"
    volumes:
    - "$PWD/mimir:/etc/grafana"
    - "mimir-storage:/var/lib/grafana"
    working_dir: /var/lib/grafana
  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    ports:
    - "3000:3000"
    volumes:
    - "$PWD/grafana:/etc/grafana"
    - "grafana-storage:/var/lib/grafana"
  minio:
    image: minio/minio
    container_name: minio
    environment:
    - "MINIO_ROOT_USER=admin"
    - "MINIO_ROOT_PASSWORD=hogehoge"
    ports:
    - "9000:9000"
    - "9001:9001"
    volumes:
    - "minio-storage:/data"
    command: server /data --console-address ":9001"
  loki:
    image: grafana/loki:2.9.4
    container_name: loki
    command: ["--config.file=/etc/grafana/config.yaml"]
    environment:
    - "JAEGER_AGENT_HOST=agent"
    - "JAEGER_AGENT_PORT=6831"
    - "JAEGER_SAMPLER_TYPE=const"
    - "JAEGAR_SAMPLER_PARAM=1"
    ports:
    - "3100:3100"
    volumes:
    - "$PWD/loki:/etc/grafana"
    # - "loki-storage:/var/lib/loki"    # permission denied. uid 10001
    - "/var/lib/loki:/var/lib/loki"     # mkdir /var/lib/loki; chown 10001:10001 /var/lib/loki
    working_dir: /var/lib/loki
  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    command: ["--config.file=/etc/grafana/config.yaml"]
    ports:
    - "3200:3200"   # tempo
    - "14317:4317"   # otlp grpc.   4317:4317 は agent と競合するので変更
    volumes:
    - "$PWD/tempo:/etc/grafana"
    - "tempo-storage:/var/lib/tempo"
    working_dir: /var/lib/tempo
  agent:
    image: grafana/agent:v0.40.3
    container_name: agent
    ports:
     - "4317:4317"   # otlp grpc
     - "4318:4318"   # otlp http
     - "9411:9411"   # zipkin
     - "14250:14250" # jaeger grpc
     - "6831:6831"   # jaeger compact
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "$PWD/agent:/etc/grafana"
    - "agent-storage:/var/lib/grafana-agent"
    command: ["--config.file=/etc/grafana/agent.yaml"]
volumes:
  grafana-storage: {}
  grafana2-storage: {}
  mimir-storage: {}
  minio-storage: {}
  loki-storage: {}
  tempo-storage: {}
  agent-storage: {}
