apiVersion: 1
datasources:
  - name: Alertmanager
    uid: alertmanager
    type: alertmanager
    url: http://mimir:8080/
    access: proxy
    editable: true
    jsonData:
      httpHeaderName1: X-Scope-Orgid
    secureJsonData:
      httpHeaderValue1: keisuk-t
