apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://mimir:9009/prometheus
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      httpHeaderName1: X-Scope-Orgid
      prometheusType: Mimir
    secureJsonData:
      httpHeaderValue1: balthasar00
  - uid: prometheus-journal
    name: Prometheus.journal
    type: prometheus
    url: http://mimir:9009/prometheus
    access: proxy
    editable: true
    jsonData:
      httpHeaderName1: X-Scope-Orgid
      prometheusType: Mimir
    secureJsonData:
      httpHeaderValue1: journal
  - uid: prometheus-all
    name: Prometheus.all
    type: prometheus
    url: http://mimir:9009/prometheus
    access: proxy
    editable: true
    jsonData:
      httpHeaderName1: X-Scope-Orgid
      prometheusType: Mimir
      manageAlerts: false
    secureJsonData:
      httpHeaderValue1: balthasar00|journal