apiVersion: 1
datasources:
  - uid: tempo
    name: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpHeaderName1: X-Scope-OrgID
      lokiSearch:
        datasourceUid: loki
      nodeGraph:
        enabled: true
      search:
        filters:
          - id: service-name
            operator: "="
            scope: resource
            tag: service.name
          - id: span-name
            operator: "="
            scope: span
            tag: name
      serviceMap:
        datasourceUid: prometheus
      tracesToLogsV2:
        customQuery: false
        datasourceUid: loki
        filterByTraceID: true
        spanEndTimeShift: 5m
        tags: []
    secureJsonData:
      httpHeaderValue1: keisuk-t