server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: ./positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    headers:
      X-Scope-OrgID: "keisuk-t"

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 10s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
    pipeline_stages:
    - match:
        selector: '{container="loki"}'
        stages:
        - logfmt:
            mapping:
              traceID:
    - structured_metadata:
        traceID:
